MD013:
  # Number of characters
  line_length: 160
  # Number of characters for headings
  heading_line_length: 160
  # Number of characters for code blocks
  code_block_line_length: 160
  # Include code blocks
  code_blocks: false
  # Include tables
  tables: false
  # Include headings
  headings: false
  # Include headings
  headers: false
  # Strict length checking
  strict: false
  # Stern length checking
  stern: false
