# Golang

- id: go-fmt
  name: "go fmt"
  entry: hooks/go/run-go-fmt.sh
  types: [go]
  language: "script"
  description: "Runs `gofmt`, requires golang"

- id: go-imports
  name: "go imports"
  entry: hooks/go/run-go-imports.sh
  types: [go]
  language: "script"
  description: "Runs `goimports`, requires golang"

- id: go-vet
  name: "go vet"
  entry: hooks/go/run-go-vet.sh
  types: [go]
  language: "script"
  description: "Runs `go vet`, requires golang"

- id: go-lint
  name: "go lint"
  entry: hooks/go/run-go-lint.sh
  types: [go]
  language: "script"
  description: "Runs `golint`, requires https://github.com/golang/lint"

- id: go-cyclo
  name: "go-cyclo"
  entry: hooks/go/run-go-cyclo.sh
  types: [go]
  language: "script"
  description: "Runs `gocyclo`, requires https://github.com/fzipp/gocyclo"
  args: [-over=15]

- id: no-go-testing
  name: "Check files aren't using go's testing package"
  entry: 'testing\.T'
  files: 'test_.*\.go$'
  language: "pygrep"
  description: "Checks that no files are using `testing.T`, if you want developers to use a different testing framework"

- id: golangci-lint
  name: "golangci-lint"
  entry: hooks/go/run-golangci-lint.sh
  types: [go]
  language: "script"
  pass_filenames: false
  description: "Runs `golangci-lint`, requires https://github.com/golangci/golangci-lint"

- id: go-critic
  name: "go-critic"
  entry: hooks/go/run-go-critic.sh
  types: [go]
  language: "script"
  description: "Runs `go-critic`, requires https://github.com/go-critic/go-critic"

- id: go-unit-tests
  name: "go-unit-tests"
  entry: hooks/go/run-go-unit-tests.sh
  types: [go]
  language: "script"
  description: "Runs `go test`"

- id: go-build
  name: "go-build"
  entry: hooks/go/run-go-build.sh
  types: [go]
  language: "script"
  description: "Runs `go build`, requires golang"

- id: go-generate
  name: "go-generate"
  entry: hooks/go/run-go-generate.sh
  types: [go]
  language: "script"
  description: "Runs `go generate`, requires golang"

- id: go-mod-tidy
  name: "go-mod-tidy"
  entry: hooks/go/run-go-mod-tidy.sh
  types: [go]
  language: "script"
  description: "Runs `go mod tidy -v`, requires golang"

- id: go-mod-vendor
  name: "go-mod-vendor"
  entry: hooks/go/run-go-mod-vendor.sh
  types: [go]
  language: "script"
  description: "Runs `go mod vendor`, requires golang"

# Shell

- id: shellcheck
  name: Shellcheck Bash Linter
  entry: hooks/sh/shellcheck.sh
  files: '\.sh$'
  language: script
  description: "Performs linting on bash scripts, requires shellcheck"

# Markdown
- id: markdownlint
  name: Check markdown files
  description: Check markdown files and flag style issues, auto-fixing if possible
  entry: hooks/markdown_lint.sh
  language: script
  types: ["markdown"]
